/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const NotificationResponseDtoSchema = z.object({
    id: z.string(),
    type: z.string(),
    title: z.string(),
    body: z.string().nullable(),
    link: z.string().nullable(),
    entityType: z.string().nullable(),
    entityId: z.string().nullable(),
    readAt: z.coerce.date().nullable(),
    createdAt: z.coerce.date(),
});
export type NotificationResponseDto = z.infer<typeof NotificationResponseDtoSchema>;

export const ListNotificationsResponseDtoSchema = z.object({
    items: z.array(NotificationResponseDtoSchema),
    meta: z.object({
    total: z.number(),
    page: z.number(),
    pageSize: z.number(),
    pageCount: z.number(),
  }),
});
export type ListNotificationsResponseDto = z.infer<typeof ListNotificationsResponseDtoSchema>;

export const UnreadCountResponseDtoSchema = z.object({
    count: z.number(),
});
export type UnreadCountResponseDto = z.infer<typeof UnreadCountResponseDtoSchema>;
