/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const LogTransportExpenseDtoSchema = z.object({
    payeeType: z.enum(["SUPPLIER", "STAFF", "OTHER"]),
    payeeRef: z.record(z.string(), z.unknown()),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    method: z.enum(["CASH", "BANK", "PETTY_CASH", "MPESA", "CHEQUE"]),
    narrative: z.string(),
});
export type LogTransportExpenseDto = z.infer<typeof LogTransportExpenseDtoSchema>;

export const TransportExpenseResponseDtoSchema = z.object({
    id: z.string(),
    routeId: z.string(),
    voucherId: z.string(),
    voucherNumber: z.string(),
    amount: z.string(),
    status: z.string(),
    narrative: z.string(),
    createdAt: z.string(),
});
export type TransportExpenseResponseDto = z.infer<typeof TransportExpenseResponseDtoSchema>;

export const TransportRouteSummaryDtoSchema = z.object({
    routeId: z.string(),
    totalIncome: z.string(),
    totalExpense: z.string(),
});
export type TransportRouteSummaryDto = z.infer<typeof TransportRouteSummaryDtoSchema>;
