services:
  nginx:
    networks:
      kong_network:
        aliases:
          - klickit-erp
  minio:
    networks:
      kong_network:
        aliases:
          - klickit-erp-storage

networks:
  kong_network:
    external: true
    # Temporary fixed name while validating the shared Kong/ERP network.
    name: kong-erp-network
