/**
 * AUTO-GENERATED by packages/contracts/codegen/generate-zod-schemas.ts.
 * DO NOT EDIT BY HAND — regenerate with `pnpm --filter contracts run generate:zod`
 * (or `generate`, which also refreshes the OpenAPI-derived types).
 *
 * Mirrors the class-validator DTO of the same name in packages/server/src —
 * see that file for the authoritative validation rules; this zod schema is a
 * best-effort structural + constraint mirror of it (docs/phase-3/01-system-architecture.md
 * §5's Validation row: "DTO (class-validator) at edge; zod mirrors in contracts for frontend").
 */
import { z } from "zod";

export const CreateBankExternalTransferDtoSchema = z.object({
    sourceAccountId: z.string().uuid(),
    beneficiaryName: z.string().max(120),
    beneficiaryBankName: z.string().max(120),
    beneficiaryBranch: z.string().max(120).optional(),
    beneficiaryAccountNo: z.string().max(40),
    debitAccountId: z.string().uuid(),
    amount: z.string().regex(/^-?\d+(\.\d+)?$/),
    feeAmount: z.string().regex(/^-?\d+(\.\d+)?$/).optional(),
    referenceNo: z.string().max(60).optional(),
    expectedClearingDate: z.string().optional(),
});
export type CreateBankExternalTransferDto = z.infer<typeof CreateBankExternalTransferDtoSchema>;

export const UpdateBankExternalTransferReferenceDtoSchema = z.object({
    referenceNo: z.string().max(60),
});
export type UpdateBankExternalTransferReferenceDto = z.infer<typeof UpdateBankExternalTransferReferenceDtoSchema>;

export const BankExternalTransferResponseDtoSchema = z.object({
    id: z.string(),
    number: z.string(),
    sourceAccountId: z.string(),
    beneficiaryName: z.string(),
    beneficiaryBankName: z.string(),
    beneficiaryBranch: z.string().nullable(),
    beneficiaryAccountNo: z.string(),
    debitAccountId: z.string(),
    amount: z.string(),
    status: z.string(),
    approvalRef: z.string().nullable(),
    journalId: z.string().nullable(),
    feeAmount: z.string().nullable(),
    referenceNo: z.string().nullable(),
    expectedClearingDate: z.string().nullable(),
});
export type BankExternalTransferResponseDto = z.infer<typeof BankExternalTransferResponseDtoSchema>;
